"""Write the design-phase briefs and exact imagegen prompts. No product changes."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
THEMES = [
    dict(id="01-akshara", name="Akshara · The living manuscript", palette="warm ivory #F5EFE3, ink #252018, muted burnt-sienna #AC551F", type="a refined, high-contrast editorial serif for headlines and a clean humanist sans serif for navigation and all application UI", art="a cinematic, finely textured sandstone bas-relief inspired by the Mahabharata's dictation and scribe tradition: a dignified elephant-headed Ganesha seated writing a manuscript, with Vyasa seated nearby; these are respectful stone figures, not cartoon characters. The carved tableau occupies only the right third. Behind them a softly lit ancient Indian library recedes into warm dust and sandstone haze. Show sculptural material, thin manuscript leaves, shallow carving depth, and believable side lighting; no battle imagery or busy religious symbols", detail="an extremely wide, quiet sandstone library panorama with stone shelves and manuscript niches, then a macro photograph of layered palm-leaf manuscript edges, ending in a warm dawn colonnade", thesis="Ancient authorship translated into a warm editorial AI workspace.", metaphor="The scribe turns a thought into a lasting manuscript.", hero_note="Warm, tactile sandstone on the right; exceptionally calm ivory copy area on the left.", risk="The scribe must remain a background artwork; miniature carving detail may be reduced on mobile."),
    dict(id="02-astra", name="Astra · Intent into impact", palette="near-black charcoal #11171B, warm off-white #F2EFE7, brushed antique bronze #B78846", type="a crisp contemporary neo-grotesk sans serif with restrained tracking for large headlines, the same family for utility UI, plus a tiny monospaced chapter label", art="a cinematic museum photograph of a single monumental antique-bronze Arjuna-inspired archer sculpture, side profile, facing right, drawing a graceful curved bow toward an empty horizon. Upper body and bow silhouette dominate the right third; retain anatomically plausible arms and bow string. This is a quiet sculpture study, never a battle, never a game character. Matte black plinth, fine metal patina, dramatic narrow warm rim light, faint atmosphere, large empty dark left side. An understated partial chariot-wheel relief may be visible at the far right edge, out of focus", detail="a wide chiaroscuro bronze chariot-wheel detail against charcoal, then a close-up of a bronze bow curve with restrained specular highlights, ending in a vast dark horizon with a narrow dawn line", thesis="A precise, cinematic page where focused intent becomes a finished deliverable.", metaphor="An archer's concentration becomes the product's deliberate creation sequence.", hero_note="Dark negative space meets a single sharply lit bronze silhouette.", risk="Dark UI must keep sufficient body-text contrast; the bronze silhouette must stay legible without glow effects."),
    dict(id="03-neel", name="Neel · The story garden", palette="warm pearl #F3F1EA, deep ink-blue #172E5B, a single royal-indigo accent #285CCB", type="an elegant moderate-contrast serif for large editorial headlines and a restrained modern sans serif for the interface", art="a bespoke Pichwai-inspired Indian miniature painting, translated into a spacious contemporary digital mural. Deep indigo dusk, two graceful peacocks, a quiet lotus pond, slender kadamba trees, cream cloud contours, delicate hand-painted edges and tiny restrained gold pigment flecks. It evokes Krishna's garden through landscape and peacock motifs without depicting a deity. Place the detailed garden mostly in the right third and along the outer edges, leaving the upper-left ivory-to-soft-blue atmospheric area exceptionally empty. No dense mandala wallpaper, no ornament behind letters, no psychedelic cosmic imagery", detail="a panoramic painted lotus pond with distant tree silhouettes, then a close-up painted lotus leaf and a feather contour, ending in an indigo garden at dawn", thesis="A distinctive Indian painted world surrounding a calm and contemporary product.", metaphor="A thought grows through ordered chapters into a complete story.", hero_note="A restrained hand-painted garden with white product surfaces and blue control accents.", risk="The mural needs separate desktop and mobile crops; excessive ornament must be avoided."),
    dict(id="04-sabha", name="Sabha · The hall of ideas", palette="luminous limestone #F4F2EC, graphite #2D302E, muted terracotta #B35A43", type="a confident contemporary sans serif for headlines and UI, with spacious line-height and subtle optical weight differences", art="a photorealistic, architectural editorial photograph of an imagined ancient Indian assembly hall inspired by the Mahabharata's Sabha: pale limestone columns, carefully carved jali screens, a distant shallow reflecting pool, warm morning light, long clean shadows, serene monumental scale. The corridor and arches occupy the right third, with a quiet almost-white plaster wall and light haze on the left for headline legibility. No people, no throne, no tourist signage, no deity, no clutter, no generic Greco-Roman columns. Image should feel like a premium architecture publication, grounded stone textures and believable perspective", detail="a wide sunlit Indian stone colonnade with a distant reflecting pool, then an abstract photographic jali-shadow study across limestone, ending in an open light-filled assembly courtyard", thesis="An architectural, bright and assured home for structured ideas.", metaphor="The assembly hall gives ideas room and order.", hero_note="Pale architectural photography, precise sans typography, one terracotta action color.", risk="Do not let the architecture look like a hotel homepage; keep the AI editor prominent in the lower half."),
    dict(id="05-vanam", name="Vanam · Wisdom in the wild", palette="misty celadon #EBEEE5, deep forest ink #183B32, muted emerald accent #2F6454", type="a warm literary serif for headlines and a readable contemporary sans serif for the application and controls", art="an original Indian epic-inspired forest painting in the visual language of a restrained Kerala mural and hand-painted book illustration, with flat layered forest forms, fine ink contours and natural pigment grain. A very small dignified sage writing on palm leaves sits beneath a huge banyan tree in the far-right third, surrounded by subtle roots and river mist. The sage is part of the landscape, not a mascot. Celadon dawn light opens into generous pale empty space on the left. Use deep green canopy masses, soft ivory mist, subtle leaf shapes, no saturated rainbow, no decorative frames, no fantasy monsters, no busy religious motifs", detail="a wide forest river panorama in the same muted mural style, then a quiet close-up palm-leaf manuscript painting beneath banyan roots, ending in a soft green clearing at dawn", thesis="A scholarly, organic page where knowledge becomes clear, useful work.", metaphor="Forest manuscript traditions meet a practical AI writing studio.", hero_note="Banyan silhouettes and celadon mist balance a clean literary interface.", risk="The forest must read as an art direction for writing software rather than a wellness product."),
]

COMMON = """Use case: ui-mockup.
Asset type: one high-fidelity, implementable website design mockup for the logged-out DocBuilder AI landing page. It is a front-facing flat screenshot, NOT a photo of a screen, device mockup, moodboard, collage, or presentation slide.
Product truth: DocBuilder AI creates structured Word documents or PowerPoint presentations. The user chooses a title and output type, asks AI for an outline, generates section content, optionally enables web research, edits and refines individual sections with natural-language instructions, reorders sections, and exports DOCX or PPTX. The existing product has four PPTX themes. Treat the application shown here as a proposed visual redesign of those real capabilities. Do not invent collaborative cursors, upload workflows, PDF export, fake customer logos, revenue metrics, ratings, speed guarantees, confidence scores, or pricing.
Visual quality: exceptionally premium, art-directed, carefully aligned, quiet and editorial. Modest confident sans-serif type, coherent spacing, meaningful image crops, clean flat application controls, hairline dividers, restrained radius, one action accent. Rich artwork and rigorous modern UI must coexist. Everything can be built with ordinary HTML/CSS, bitmap background images and a sticky scroll sequence using opacity and transforms. No impossible holograms, 3D UI perspective, floating shards, elaborate physics, or giant ornamental card grids.
Typography: readable real English, crisp anti-aliased letters, natural kerning, no faux-language, no gibberish. Exact supplied copy must be reproduced verbatim. Where dense document prose would be too small, use restrained light-gray text lines beneath a real heading; never fill the page with tiny noisy text. All marketing copy has high contrast against a calm image area or solid surface.
"""

HERO = """Screen 01 — Refined hero and initial showcase entry.
ONE flat, front-facing desktop website screenshot, 16:10 landscape. NOT a moodboard or photo of a screen. Treat this as a website ready for a premium AI software brand.
Precise layout at virtual 1440x900: a full-width quiet thematic page with a 72px navigation area and 96px inside gutters. Navigation baseline y=38: small refined wordmark 'DocBuilder AI' at x=96, 22px, regular-medium weight. Middle navigation 'Workflow', 'Capabilities', 'FAQ' in 14px with 32px gaps. Right 'Log in' and a SMALL 120x36 dark or pale pill button 'Start creating'. No thick nav bar or hard border.
Hero headline begins x=96, y=162. It must occupy only 490px width and roughly 116px height. EXACT headline in two lines: 'Your ideas.' then 'Beautifully built.' Contemporary sans serif, 52px virtual size, medium 500 weight, slightly tight tracking, line-height 1.08. Absolutely NO large black serif, no 100px type, no ultra-bold poster typography. Make the sentence about the scale of Devin's restrained desktop headline. Keep huge areas of deliberate empty space around it, especially the center of the page.
Supporting copy at x=96,y=290, 18px and muted ink, two short lines maximum: 'Create structured documents and presentations with AI.' At x=96,y=352, a 142x42 restrained dark/pale pill button 'Start creating'; next to it, 'Explore the workflow' as a 14px plain text link with a fine arrow. The accent color is NOT a saturated orange or glowing UI color.
Artwork: one curated image plane occupying the rightmost 40 percent of the upper hero, roughly x=850–1440,y=80–455. It should feel like a sophisticated editorial image crop that fades naturally into the page's calm base color. Keep left and center mostly clean. It may extend to the right page edge but not turn into a dense decorative wall. Respect the theme's revised artwork brief. A small, restrained theme-art crop can reappear around the bottom outer edges. NOT a tourist postcard, not a giant devotional statue portrait, not game art, not a stock fantasy illustration. No detail behind text or navigation. Control saturation carefully.
CRITICAL: ONE wide application workspace container starts x=96,y=470,width=1248px. Its lower half continues past the bottom crop of this viewport. It occupies approximately the lower HALF of the screen and is substantial enough to become a full-screen scroll showcase. Fine 1px neutral outline, 12px corners, very faint shadow only. Do not tilt, float, stack or duplicate it; no device frame, heavy drop shadow, puffy corners or detached overlaid cards.
Workspace topbar is 46px high: small 'DocBuilder AI' at left, 'Clean Energy Outlook' centered, plain 'DOCX' label and tiny outline 'Export' button at right. Toolbar controls use 12–13px clean sans-serif; muted neutral strokes. OUTLINE sidebar is 210px wide, with small restrained 13px rows: 'Executive summary', 'Market landscape', 'Growth drivers', 'Risks', 'Conclusion'. Only the first row is selected with a whisper of theme accent and a short thin rule, not a giant colored pill. White or warm paper editor is about 790px wide, calm 52px padding, a slim simple formatting toolbar and 28px SANS-SERIF title 'Executive summary'. One short 15px paragraph may read 'A clear view of the clean energy transition, its opportunities and the decisions ahead.' Then four thin gray prose lines. Keep it visually spare and real.
Right refinement rail about 245px wide with a thin vertical divider: 13px label 'Refine section', a 90px understated plain instruction field 'Make this more concise', and a small dark/pale 'Refine' button. Do NOT add suggestion cards, colored icons, shadows or extra badges. All working text lies on solid calm surfaces. Use the theme color only in a selection stroke, a tiny mark, or one quiet progress detail. The application must look like a refined writing workspace, never chunky SaaS admin chrome.
Composition goal: thoughtful spacing and precision create the premium feeling. The hero copy is restrained, artwork curated, application clean and understated. Every region aligns to the same grid. Render ONLY this one hero viewport, no lower-page sections, no labels outside the website, no multi-panel board.
"""

SHOWCASE = """Screen 02 — The same container has become a full-screen pinned showcase.
Composition: ONE landscape desktop viewport approximately 16:10, virtual 1440 by 900. This is a middle scroll state, not another hero. The application shell fills the entire viewport edge-to-edge with square outer corners. The hero headline and marketing navigation are now offscreen. There is no surrounding page border, no miniaturized floating window, no collage, no browser toolbar. At the top, a restrained 76px narrative band in the theme's dark ink color contains 'From idea to finished work' at left and four clear sequential chapter controls: '01 Outline', '02 Generate', '03 Refine', '04 Export'. '03 Refine' is active, with the theme's accent underline. A small thin progress line spans below it, about two-thirds filled. This band is part of the showcase, not a new app feature.
Application below: topbar 56px with 'DocBuilder AI', project 'Clean Energy Outlook', 'DOCX', and 'Export'. Left sidebar 245px with five outline rows: 'Executive summary', 'Market landscape', 'Growth drivers', 'Risks', 'Conclusion'. 'Growth drivers' is active, emphasized with a subtle accent background and a small side rule. Sidebar background is a neutral theme-tinted surface. Center is a generous solid paper editor, about 775px wide, with a real formatting toolbar, selected heading 'Growth drivers', and three short paragraphs with strong typographic hierarchy. One paragraph is softly selected with a single pale-accent highlight; no inline fake sources, no RAG confidence scores. Document page has comfortable 70px inner margins. Dense text can be restrained gray lines but headings and controls are readable.
Right refinement rail, approximately 330px, carries the label 'Refine section', a simple 120px-high instruction field reading 'Make this more concise and connect it to the next section.', an accent button 'Refine', and a clean separated area labelled 'Refinement history'. Two utility rows read 'Make this more concise' and 'Improve the transition', each with small thumbs-up / thumbs-down outline controls. At the foot of the editor, a quiet status reads 'Your changes stay editable'. Near bottom-left of the narrative area show 'Scroll to continue' and a subtle vertical scroll indicator. No timer, no autonomous autoplay claim.
Storytelling intent: the viewer immediately understands that scroll is advancing the same project through creation, not opening unrelated product cards. Only the active chapter needs accent color. Use the same wordmark, palette, typography, sidebar style, and component radius as Screen 01. Artwork may appear only as a narrow subtle theme-colored crop in the narrative band or sidebar edge, never as noisy texture beneath editable text.
Implementability: flat DOM panels, a sticky viewport, chapter text swaps, local row selection, document content crossfades, and CSS progress updates. No impossible morphing object, no mandatory WebGL. Render only this full-screen pinned refinement state.
"""

AFTER = """Screen 03 — Continuous lower-page composition after the pinned showcase releases.
Composition: ONE tall full-width desktop web-page screenshot, approximately 2:3 aspect ratio, with a virtual page width of 1440px and a visible page length around 2160px. It is a coherent continuation of the same website, not a moodboard, not three detached screens, no device outlines or browser chrome. At the top edge, show only a very slim last strip of the application showcase with chapter '04 Export' and a subtle dividing line. The pinned area has released and normal page content now follows in a clear top-to-bottom flow. Keep generous 88px outer gutters and strong whitespace between major sections. Three meaningful sections plus FAQ/footer; no repeated card mosaics.
First section, occupying roughly the top 500px: a wide atmospheric crop from the theme's described lower-page imagery. Overlay or sit beside its calm tonal area a large headline 'Depth in every section.' and short supporting line 'Generate with web research. Refine with the whole document in view.' The main composition is an asymmetric editorial row: the text is on a calm solid or dark-scrim area at left, and one flat paper-like product fragment at right shows section heading 'Market landscape', a clear toggle labelled 'Use web research' switched on, a few readable prose lines, and a tiny label 'Section context'. Do not invent citations UI or show fake source credibility percentages. Image remains visibly present across at least one third of this section, with controlled crops and no details behind typography.
Second section, approximately 400px: reverse the previous editorial composition so an image-backed product fragment is on the LEFT and text is on the RIGHT, with substantial negative space between them. Use the second thematic image crop behind a clean fragment of an outline and refinement instruction. Heading on the right: 'Keep the whole story in view.' Supporting line: 'Refine a section with the outline and its neighbours in context.' A tiny chapter label '02 / REFINE' is optional. This alternating layout borrows the spacious product-led storytelling rhythm of the provided Devin screenshots without copying any brand assets or wording.
Third section, about 500px: calm theme-colored solid background with a tall typographic title on the left: 'Made for the work ahead.' Then two equal broad artifact previews in an open grid without chunky rounded cards: a paper DOCX report preview titled 'Clean Energy Outlook' with generous margin and section typography; beside it a 16:9 slide preview titled 'The energy transition' with a simple editorial bar chart and restrained themed imagery. Exact descriptive labels 'Word documents' and 'PowerPoint presentations' sit beneath each artifact, and a short quiet line 'Edit every section. Choose your presentation theme. Export when ready.' No PDF, no template marketplace, no multiple artifact copies, no fake customer claims.
Fourth section: a simple FAQ area with a hairline divider, heading 'A few useful answers' and three open-layout rows. Row 1 question 'What can I create?' answer 'Structured documents and presentations.' Row 2 question 'Can I edit the result?' answer 'Yes. Edit and refine each section.' Row 3 question 'How do I export?' answer 'Download your DOCX or PPTX file.' Use plain chevrons at row right and concise exact text, not placeholder gibberish.
Final conversion block: a wide, atmospheric image-backed closing section using the third described lower-page image, with very restrained scrim or empty sky ensuring perfect contrast. Large text 'Make your next idea real.' and one solid button 'Start creating'. A compact quiet footer beneath shows 'DocBuilder AI', links 'Workflow', 'Capabilities', 'FAQ', 'Log in', and the line 'Documents. Presentations. Your ideas.' Maintain the same visual identity and accent color as both earlier screens. Do not add made-up legal pages, pricing, contact sales, testimonials, team counts, or logo clouds.
Use a different background crop for each image-led section to create narrative progression, but preserve one coherent art style. The screenshot must show the capability story, output artifacts, FAQ and final CTA, not merely a decorative tall landscape.
"""

# Revised after the user rejected the literal statue hero and oversized serif UI.
for theme in THEMES:
    theme["type"] = "one refined modern sans-serif family similar in proportions to a contemporary humanist grotesk; medium 48–56px marketing headings, 14px controls, calm 28px application titles; no huge bold serif"
THEMES[0].update(art="a sophisticated near-monochrome editorial artwork: layers of ancient palm-leaf manuscript edges and a soft sandstone river gorge at dawn, photographed with matte archival texture. In the distant right-side rock face, a very small fine charcoal mural of Vyasa dictating to a scribe quietly connects this to Mahabharata authorship. Figures occupy less than ten percent of the image and are not foreground deity portraits. Pale sand, natural grain, soft raking light, calm negative space, no golden god-ray spectacle, no dense library wall, no ornate devotional statues", hero_note="Pale manuscript textures and a tiny epic scribe mural; restrained sans-serif copy and neutral actions.", palette="pale warm stone #F2F0EA, soft charcoal #282B2A, subtle clay accent #8B6954")
THEMES[1].update(art="a refined cinematic still-life image of one cropped antique-bronze bow curve and a very distant tiny chariot silhouette across a misty charcoal horizon, evoking Arjuna's focus. Bronze patina in muted low-saturation rim light, negative space, no giant muscular warrior, no glowing particles, no game art. The curved bow is a clean striking image shape along the right edge, not a background for typography")
THEMES[2].update(art="an original contemporary interpretation of Pichwai painting: a single large elegant indigo peacock silhouette cropped at the far-right edge, two sparse pale lotus forms, delicate matte natural pigment and hazy blue sky. The visual is spacious, low saturation and museum-print quality; tiny hand-painted linework, subtle cream contour, no dense gold ornament, no crowded garden, no mandala wallpaper. It evokes Krishna's garden without a foreground deity")
THEMES[3].update(art="a premium architecture-publication photograph of a pale Indian assembly hall inspired by Sabha: one monumental limestone arch, a thin jali screen, a distant shallow reflecting pool and soft morning side light. Very clean geometry, subtle tactile stone, spacious crop, nearly monochrome, no gaudy palace, no hotels, no statues, no busy carvings. Large blank pale wall at left; architectural forms only at far right")
THEMES[4].update(art="a quiet contemporary Indian mural-style landscape of a single monumental banyan canopy and river mist, painted in muted celadon and deep forest ink with fine pigment texture. A tiny distant sage with a palm-leaf manuscript under the far-right tree evokes epic forest scholarship but occupies under five percent of the image. Asymmetric open sky, strong spare tree silhouette, no lush wallpaper, no cute cartoon, no huge character, no wellness icons")

manifest = []
for theme in THEMES:
    folder = ROOT / theme["id"]
    (folder / "prompts").mkdir(parents=True, exist_ok=True)
    (folder / "mockups").mkdir(exist_ok=True)
    art = f'\nTheme: {theme["name"]}.\nVisual thesis: {theme["thesis"]}\nColor palette: {theme["palette"]}. Use one accent, never a generic blue/purple gradient.\nTypography: {theme["type"]}. At most two families.\nHero artwork: {theme["art"]}.\nLower-page imagery: {theme["detail"]}.\nRelationship to the product: {theme["metaphor"]} Do not put the mythology metaphor into utility labels; keep the application in clear modern English.\n'
    for stem, spec in [("01-hero", HERO), ("02-scroll-showcase", SHOWCASE), ("03-after-showcase", AFTER)]:
        prompt = COMMON + art + "\n" + spec
        (folder / "prompts" / f"{stem}.txt").write_text(prompt)
        manifest.append(dict(theme=theme["id"], screen=stem, prompt=f'{theme["id"]}/prompts/{stem}.txt', output=f'{theme["id"]}/mockups/{stem}.png', status="pending"))
    (folder / "DIRECTION.md").write_text(f'# {theme["name"]}\n\n{theme["thesis"]}\n\n- Palette: {theme["palette"]}.\n- Type: {theme["type"]}.\n- Art: {theme["art"]}.\n- Product connection: {theme["metaphor"]}\n- Hero composition: {theme["hero_note"]}\n- Implementation consideration: {theme["risk"]}\n\n## Page sequence\n\n1. Hero with large workspace in its lower half.\n2. Workspace expands, pins, and progresses through Outline → Generate → Refine → Export.\n3. Capability detail with thematic background imagery.\n4. Document and presentation examples.\n5. FAQ and image-backed final CTA.\n\nThe mockups propose styling for real product functions; they do not claim the current application already looks this way. See the shared SCROLL-STORY.md for interaction and mobile behavior.\n')
(ROOT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
