"""Generate dense future-state laptop briefs; preserve image reviews."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
THEMES = [
 dict(id="01-akshara", name="Akshara · The epic scribe", palette="porcelain ivory #F1EDE4, carbon #24231F, deep vermilion #8E342E; ultramarine and antique gold in art", art="A bespoke Indian epic oil painting with museum-quality pigment and a contemporary editorial crop. Ganesha is unmistakably elephant-headed, wearing a restrained gold crown and red silk dhoti, seated writing on palm-leaf manuscripts; elderly bearded Vyasa in ivory and saffron robes dictates beside him. Their faces, hands and manuscripts are large and clearly recognizable at thumbnail size. Layer indigo river water, carved Indian pavilion columns, painted banyan foliage, palm-leaf bundles and a woven crimson textile into a rich authored scene. Matte oil pigment, believable cloth folds, finely drawn eyes and warm natural side light. A grand painting of authorship, never plastic 3D devotional art or stock statues.", crops="Ganesha's hand and manuscript with red cloth; Vyasa and a river beneath banyan branches; a carved pavilion framing a manuscript table", thesis="An unmistakable epic authorship painting around a precise contemporary writing studio.", risk="Separate figure, foliage and ground layers for responsive crops. Respectful decorative imagery."),
 dict(id="02-astra", name="Astra · The guided draft", palette="midnight navy #111C27, blue-gray paper #DFE9E8, muted copper #B77949; lapis and rust in art", art="An original richly painted Mahabharata-inspired writing studio. Recognizable blue Krishna with a peacock-feather crown sits beside Arjuna at a broad carved desk in a river pavilion. Krishna reviews an open source manuscript and points at an arranged outline of paper sections. Arjuna writes at a slim modern laptop showing a simple document page, with printed report sheets and slide-storyboard thumbnails beside it. Krishna is a guide and Arjuna is the author. Fine natural oil pigment, mature brush detail, indigo river, rust-red textiles and warm lamplight create layered epic imagery tied directly to researching, drafting and presenting. No weapons, bows, chariots, armor, soldiers, battlefield, aggression or game art.", crops="Krishna reviewing a source manuscript; Arjuna drafting at a desk; arranged document sections and slide storyboard", thesis="Krishna and Arjuna shape a report in an epic writing studio, beside a midnight-and-copper application.", risk="Readable dark chrome; contrasting blue-gray editor paper."),
 dict(id="03-neel", name="Neel · The painted story garden", palette="warm white #F5F1E7, indigo #162E57, cobalt #315BA8; lotus pink and leaf green in art", art="A magnificent contemporary Pichwai-inspired Indian garden painting. Clearly recognizable blue Krishna with a peacock-feather crown plays a flute beneath a kadamba tree, in cream and yellow cloth with fine gold edging. Two peacocks, a layered lotus pond, dense leaves, graceful white cows and a scalloped pavilion form a sophisticated narrative tableau. Precise hand-painted mineral pigment, matte paper texture, richly layered flat space and tiny natural gold details. Krishna is substantial and immediately visible, never a faint symbol. No generic blue gradient, mandala wallpaper or cartoon mascot.", crops="Krishna's flute and crown; dense lotus pond and peacock; pavilion behind kadamba leaves", thesis="A richly painted Krishna garden gives a crisp cobalt-and-paper workspace character.", risk="Separate image crops; no ornament beneath utility text."),
 dict(id="04-sabha", name="Sabha · The epic assembly", palette="limestone #EDE9DF, aubergine #342D3B, plum #634558; saffron and verdigris in art", art="An original richly detailed Indian miniature painting of the Mahabharata assembly hall. A cutaway palace with scalloped arches and jali screens reveals seated Pandava princes, an elder scholar and clearly blue Krishna in a peacock crown discussing a manuscript. A scribe records the meeting on palm leaves. Carpets, painted niches, a green reflecting pool and ordered columns create intricate layers. Deliberate architectural geometry and legible figure groups, not a noisy crowd. Matte gouache, fine ink contours, paper grain, lapis and terracotta details. Recognizable mythological narrative, not an empty hotel colonnade.", crops="palace assembly and scribe; arches with Krishna and cream robes; reflecting pool and court carpet", thesis="An intricate epic assembly frames a rational compact product composition.", risk="Retain recognizable figure groups in mobile art crops."),
 dict(id="05-vanam", name="Vanam · The forest manuscript", palette="celadon #E6EADF, forest #18382E, emerald #36654E; ochre and burnt orange in art", art="An original Kerala-mural-inspired epic forest illustration with refined natural pigments and crisp fine contours. Dignified white-bearded Vyasa writes palm-leaf manuscripts beneath a sprawling banyan; blue Krishna in a peacock-feather crown listens nearby. Both figures are substantial and clearly mythological. Layer large banyan roots, rich green foliage, river reflections, manuscript bundles, ochre robes, white cranes and stone steps. Intricate authored botanical detail, rhythmic flat shapes, refined copper details, mature museum-print finish. No anonymous tiny sage, blank mist field, wellness stock image or cute cartoon.", crops="Vyasa's manuscript and roots; Krishna amid layered leaves; cranes beside a river and manuscripts", thesis="A lush epic forest mural gives a scholarly green writing studio warmth and density.", risk="Clear software promise; modern plain-English controls.")
]

SURFACES = {
 "01-akshara": "Deep burgundy #65362F topbar with ivory labels; warm sand #E7D8C0 outline; pale parchment #F8EFDC editor; muted clay-beige #D8C7AD research rail; ink #2F2822 text and vermilion #8E342E controls. All panes visibly tinted, not one white rectangle. Smooth solid colors, no texture beneath prose.",
 "02-astra": "Midnight #12212C topbar; slate #1E3340 outline with chalk labels; blue-gray #DFE9E8 editor with navy ink; dark steel #223848 research rail and #2F4653 source rows with chalk labels; copper #BD8E59 controls. Toolbar #253F4F. Strong dark-versus-light architecture, not white SaaS panels with a brown button.",
 "03-neel": "Deep indigo #173C70 topbar with ivory text; soft blue #D7E3ED outline; pale mineral-paper #EEF3E8 editor with indigo ink; muted teal #C6D9DD research rail; cobalt #315BA8 actions. Rich color zoning across large container surfaces, never an all-white shell.",
 "04-sabha": "Aubergine #49334F topbar with ivory text; lavender-gray #DFD7E4 outline; pale blush-paper #F3EBF0 editor; dusty mauve #CBBBCF research rail; plum #634558 controls and dark plum ink. Refined tonal panels, not just plum buttons on white.",
 "05-vanam": "Forest #153C34 topbar with warm ivory labels; sage #BFD0C1 outline; celadon-paper #E8EDDF editor; muted fern #A9BFAE research rail; evergreen #275E49 controls and forest ink. Broad coordinated colored surfaces, not a white shell with green icons."
}

# User steering: imagery must show authorship work, and UI surfaces carry each palette.
THEMES[0]["art"] += " Add a slim modern writing laptop among the manuscripts; Vyasa compares source notes while Ganesha drafts. Their work visibly mirrors research, writing and refinement."
THEMES[2]["art"] = "A sophisticated Pichwai-inspired epic authorship garden: clearly blue Krishna with a peacock-feather crown sits at a painted garden desk, reading source notes and arranging report pages with a slim modern writing laptop and a small slide storyboard. Dense kadamba leaves, peacocks, lotus pond, white cows and a scalloped pavilion frame this creative work. Mineral pigments, matte paper grain, precise hand-painted contours, layered flat space and small natural gold details. Krishna is recognizably researching and shaping a document rather than only playing music. No battle or weapons, no generic gradient or mascot."
THEMES[2]["crops"] = "Krishna inspecting source notes; outline sheets with a painted peacock; a garden writing desk and slide storyboard"
THEMES[3]["art"] += " Treat the assembly as a working editorial meeting: Krishna reviews sources, a prince arranges document sections, and the scribe prepares a slide storyboard beside a small modern laptop. No debate about war, weapons or armor."
THEMES[4]["art"] += " Give the forest table a slim modern writing laptop and loose report drafts. Krishna reviews source notes while Vyasa revises a section and prepares a small slide storyboard. Peaceful creative work, no weapons or warfare."

COMMON = """Use case: ui-mockup.
Asset: one high-fidelity implementable DocBuilder AI website screenshot, one laptop viewport. Canvas exactly 1920x1080 pixels, landscape 16:9. Fill the entire canvas. No browser chrome, device frame, outer margins, contact sheet or tall web-page board.
Future-state product: assume docs/PRODUCT_REBUILD_PLAN.md has been successfully implemented: structured briefs and starter templates, editable outlines, source-backed generation and inspected sources, meaningful autosave, reversible refinement diffs, version checkpoints, document/slide previews, selected-section generation and format-appropriate export. This is a hypothetical future UI, not current deployment proof. Do not print planning labels within the site.
Art direction: combine compact precise application composition from the supplied Devin screenshots with the richly painted and layered world of Shopify Winter '26 Renaissance Edition. Original Indian mythological scenes and DocBuilder copy. No borrowed brand assets, names, commerce features or customer claims.
Density: substantial useful UI and rich images replace large blank gaps. Desktop nav15px; marketing headings44–48px medium sans; body17px; app controls14px; editor headings29px. Compact36–40px rows,12–20px component padding,40–56px section gaps. Clear hierarchy and alignment, never tiny unreadable controls or random boxes. Mythological figures must be sizable and unmistakable.
Finish: thin neutral dividers,6–10px utility corners,12px workspace corners, restrained natural shadow, crisp flat controls. Apply the theme's color zoning to large topbar/sidebar/editor/utility surfaces, not only tiny buttons. Smooth solid tinted paper beneath working text, readable contrasting ink. No glow, glass, puffy gradient cards, rainbow badges, huge serif headline, 3D tilted UI or generic SaaS bento.
Story: recognizable mythological figures actively research, outline, write, review and prepare a presentation. A slim modern writing laptop, source notes and slide-storyboard sheets tie the epic painting to this product, like contemporary objects within an authored historical painting. No battlefield, chariot charge, weapons, armor or war narrative.
Typography: real crisp English, natural kerning, quoted labels verbatim. Document prose may be short real sentences. No gibberish, logos, testimonials, awards, speed guarantees, fabricated metrics, unlimited generation, collaboration cursors, confidence scores or pricing promises. Mythology is artwork, not utility naming.
Sample: 'Clean Energy Outlook'. Five sections: 'Executive summary', 'Market landscape', 'Growth drivers', 'Risks', 'Conclusion'. Illustrative prose: 'Renewables are reshaping how energy is produced. Storage and grid flexibility help connect new supply to demand.' Source titles: 'Renewables 2025' / 'IEA'; 'Energy Storage' / 'US Department of Energy'. Small inline [1][2] source markers, no invented quotes or numbers.
"""

HERO = """Screen01 — compact hero and substantial lower-half application.
One1920x1080 laptop viewport. Nav y22–70, gutters x112 and1808. Left small book-outline mark plus 'DocBuilder AI'; middle 'Workflow','Capabilities','FAQ'; right 'Log in' and126x36 button 'Start creating'. No huge header bar.
Copy x112–650,y116–340. Compact40px medium sans heading in two lines exactly 'Research, write.' then 'Present with purpose.' Supporting16px two lines 'From a clear brief to a source-backed document' / 'or a presentation ready to share.' Immediately beneath:36px 'Start creating' button and plain 'Explore the workflow' link. At y347 compact line 'Brief → Research → Refine → Present'. No large empty spacer. Keep the heading below one-third of viewport width.
Right region x790–1920,y62–438 is the theme's large original epic tableau. Recognizable principal figures, rich layered scenery, textiles, manuscripts. Bold art-publication crop, layered picture planes, not a small stamp on blank sky. Art reaches right edge and continues into outer gutters around the app. Copy sits on a calm opaque/scrim area with high contrast. Keep the mythological faces visible above the editor. One small flat document/slide pair may bridge art and app around x1510,y335 without obscuring figures.
CRITICAL: ONE application workspace x112,y438,width1696, continuing below the bottom crop. About the lower60% is occupied by this substantial app. It is the same container that later expands full screen. 1px boundary,12px corners,faint shadow. No miniature window, laptop frame, tilted perspective or heavy detached card stack.
Topbar48px: DocBuilder AI, centered 'Clean Energy Outlook', small green-check 'Saved', 'History','Preview','Export DOCX'. Beneath compact36px brief strip: 'Audience: leadership' • 'Purpose: explain the transition' • 'Tone: analytical' • 'Edit brief'.
Left pane238px: 'OUTLINE'; five38px section rows with small status dots; Executive summary subtly selected. Below 'Generate selected','5 sections'. Compact 'Project brief' subsection, plain audience/tone fields.
Center about1010px:38px format toolbar with paragraph selector,bold,italic,lists,link. Paper padding48px. Heading29px 'Executive summary'; three compact prose paragraphs with source markers[1][2]; 'Key takeaways' subheading and three neat bullet lines. Real working content plus additional gray text lines. Fill available working area, not skeleton blank page. Lower contents naturally cropped.
Right rail448px: tabs 'Research','Refine','History',Research active. 'Sources for this section', compact source rows Renewables2025/IEA and EnergyStorage/USDepartmentofEnergy, include checkboxes,link icons,one-line excerpts. Below 'Add source', divider and a source detail with title,domain,short excerpt. Small '2 sources included'. Solid high-contrast surfaces, no giant colored cards.
Only this hero viewport. Rich mythology, compact copy, useful app density and careful alignment must be immediately apparent.
"""

SHOWCASE = """Screen02 — same hero container expanded into a full-screen pinned demo.
1920x1080 landscape; same palette,wordmark,art and component system as Screen01. No hero/nav, outer gutters or frame. App fills viewport, square outer corners.
Top72px narrative strip in dark theme ink, narrow rich art crop at right. Left 'From brief to finished work'. Four chapter buttons '01 Shape','02 Research','03 Refine','04 Present'; Refine active,one accent underline. Thin two-thirds progress rule. Small 'Scroll to continue'. Narrative band is landing demo orientation, not a new agent feature.
App topbar56px: DocBuilder AI,Clean Energy Outlook,green-check Saved,History,Preview,Export DOCX. Brief strip36px: Audience leadership,Tone analytical,5 sections.
Left256px: same five outline rows,Growth drivers active,first two complete. Generate selected,Add section,Project brief. Compact activity list: Outline created,Sources reviewed,Draft saved. No fake streaming timer.
Center1110px: toolbar,dense paper,heading Growth drivers,subheading Review changes. Side-by-side flat inset: LEFT 'Original',short longer prose,pale red deletion highlights; RIGHT 'Suggested',concise prose,pale green additions. Clear 'Accept changes' and 'Discard' buttons below. Three readable paragraphs with[1][2] references beneath. Real document layout, not decorative page sketch.
Right554px: Research/Refine/History tabs,Refine active. 'Refine section', instruction 'Make this more concise and connect it to the next section.', small presets 'Shorten','Clarify','Change tone',button 'Review changes'. Divider then compact 'Version history' list: Draft saved,Research added,Outline approved, 'Create checkpoint',plain 'Restore' by a previous row. Footer 'Original preserved until accepted'.
Useful density and aligned controls; art only in story strip and narrow sidebar footer, never beneath prose. One full-screen refinement viewport.
"""

CAPABILITIES = """Screen03 — image-rich capability viewport after sticky showcase releases.
One1920x1080 regular page viewport,same identity. Compact64px nav,DocBuilder AI/Workflow/Capabilities/FAQ/Log in/Start creating,gutters112px. Open editorial grid,thin rules,moderate gaps; three or more useful stories together. No tall board.
y105 heading46px 'Thoughtful work, from the first line.' Supporting17px 'Set the direction. Know the sources. Keep control of every change.'
Top row y202–661 TWO equal feature compositions,24px gap. Each roughly330px image/product region with compact caption beneath.
Left heading24px 'Start with a clear brief.' Line16px 'Choose the audience, purpose and tone. Shape an outline you can change.' First rich theme crop with recognizable figure detail,not blank gradient. Overlay a crisp flat brief editor with Audience/Leadership,Purpose/Explain the transition,Tone/Analytical; adjacent outline fragment five rows,'Generate outline'. Shallow coherent overlap,no chunky card wrapper.
Right heading24px 'Know what your draft is built on.' Line16px 'Inspect sources, keep the useful ones and add your own.' Second rich mythological crop,different scale. Flat product fragment two source rows Renewables2025/IEA,EnergyStorage/USDepartmentofEnergy,include checkboxes,excerpt,[1][2],'Add source'. Solid legible surface. Artwork remains at least half of feature illustrations; not tiny symbolism.
Bottom row y718–1080 THREE compact image-and-product tiles in an open grid,24px gaps. Tile1 rich art and diff with Original/Suggested/Accept changes,heading 'Review before you replace.' Tile2 rich art and history with Create checkpoint/Restore,heading 'A version to come back to.' Tile3 art and generation checklist3 of5 complete,Stop/Resume,heading 'Pick up where you left off.' All headings visible near bottom; short descriptions if space. Natural bottom crop,not tiny squeezed board.
Dense magazine-like composition with varied art crops and readable actual product fragments. No invented metrics,logo cloud,giant blank spacer or repeated generic bento.
"""

OUTPUTS = """Screen04 — outputs,FAQ,image-led close,one laptop viewport.
1920x1080,same theme,64px nav,gutters112px. Normal lower-page flow,not entire tall website overview.
Upper y90–588:42px 'Ready for the work ahead.' and17px 'Preview the details. Choose the layout. Export when it is ready.' Below open split: broad document at left and16:9 presentation at right; each backed by a different rich epic crop. Art visible between and around solid artifacts,no massive blank base.
Document preview510x290px: 'Clean Energy Outlook','Executive brief',thin rule,table of contents five rows. Adjacent compact export list DOCX/Markdown/HTML/Print. Caption 'Documents that keep their structure.' No PDF-download claim.
Deck preview620x290px: 'The energy transition','Clean Energy Outlook',small second flat slide 'Growth drivers' with three bullets. Slim theme controls four neutral swatches,Theme/Layout/Export PPTX. Caption 'Presentations with a point of view.' No invented numerical chart. These are separate reviewed projects,not instant format switching.
Middle y632–837 compact FAQ three open columns with thin rules. Heading 'A few useful answers'. Q 'What can I create?' A 'Structured documents and presentations.' Q 'Can I change the draft?' A 'Edit sections, review refinements and restore versions.' Q 'How do I export?' A 'Preview, then download DOCX or PPTX.' Legible exact copy,no giant accordion gaps.
Closing y879–1016 full-content-width rich crop of epic manuscript/figure scene,solid/scrim under text.38px 'Make your next idea real.' Right36px button 'Start creating'. Compact footer y1030: DocBuilder AI,Workflow,Capabilities,FAQ,Log in; 'Documents. Presentations. Your ideas.'
Finished dense page close,rich art,practical artifacts,compact informative copy. No testimonials,paid-plan tables or performance guarantees.
"""

SCREENS = [("01-hero",HERO),("02-scroll-showcase",SHOWCASE),("03-capabilities",CAPABILITIES),("04-outputs-close",OUTPUTS)]

def main():
    path=ROOT/"manifest.json"
    previous=json.loads(path.read_text()) if path.exists() else []
    reviews={(x["theme"],x["screen"]):x for x in previous}
    manifest=[]
    for theme in THEMES:
        folder=ROOT/theme["id"]
        (folder/"prompts").mkdir(parents=True,exist_ok=True)
        (folder/"mockups").mkdir(exist_ok=True)
        art=f'\nTheme: {theme["name"]}.\nPalette: {theme["palette"]}.\nApplication color zoning: {SURFACES[theme["id"]]}\nOriginal artwork: {theme["art"]}\nLower-page crop sequence: {theme["crops"]}.\n'
        for stem,spec in SCREENS:
            (folder/"prompts"/f"{stem}.txt").write_text(COMMON+art+"\n"+spec)
            item=dict(reviews.get((theme["id"],stem),{}))
            current_prompt=f'{theme["id"]}/prompts/{stem}.txt'
            item.update(theme=theme["id"],screen=stem,planned_prompt=current_prompt,brief_revision="colored-authorship-laptop-v7")
            if "image_sha256" not in item:
                item["prompt"]=current_prompt
            item.setdefault("output",f'{theme["id"]}/mockups/{stem}.png')
            item.setdefault("status","pending")
            manifest.append(item)
        (folder/"DIRECTION.md").write_text(f'# {theme["name"]}\n\n{theme["thesis"]}\n\n- Palette: {theme["palette"]}.\n- Container surfaces: {SURFACES[theme["id"]]}\n- Artwork: {theme["art"]}\n- Implementation: {theme["risk"]}\n\n## Four laptop viewports\n\n1. Compact hero with large lower-half application.\n2. Same application expanded into full-screen refinement showcase.\n3. Image-rich brief, research, refinement, history and generation stories.\n4. Document and slide outputs, FAQ, image-led close and footer.\n\nTarget 1920×1080,16:9; actual dimensions recorded after generation. Future-state concepts assume the product rebuild succeeds. See FUTURE-STATE-CONTRACT.md and SCROLL-STORY.md.\n')
    retired=[x for x in previous if (x["theme"],x["screen"]) not in {(t["id"],s) for t in THEMES for s,_ in SCREENS}]
    if retired:
        archive=ROOT/"retired-screen-manifest.json"
        saved=json.loads(archive.read_text()) if archive.exists() else []
        known={(x["theme"],x["screen"]) for x in saved}
        saved.extend(x for x in retired if (x["theme"],x["screen"]) not in known)
        archive.write_text(json.dumps(saved,indent=2)+"\n")
    path.write_text(json.dumps(manifest,indent=2)+"\n")

if __name__=="__main__":
    main()
