from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
from io import BytesIO
import markdown2
import re

class ExportService:
    @staticmethod
    def clean_html(raw_html):
        cleanr = re.compile('<.*?>')
        cleantext = re.sub(cleanr, '', raw_html)
        return cleantext

    @staticmethod
    def generate_docx(project_data):
        document = Document()
        
        # Title Page
        document.add_heading(project_data.get('title', 'Untitled Project'), 0)
        document.add_paragraph(f"Generated by AI Doc Builder")
        document.add_page_break()

        # Sections
        for section in project_data.get('outline', []):
            document.add_heading(section.get('title', 'Untitled Section'), level=1)
            
            content = section.get('content', '')
            if content:
                # Basic markdown to text conversion (stripping HTML tags for now as python-docx doesn't support HTML)
                # Ideally we would parse markdown and apply styles, but for MVP we strip tags or keep raw text if simple
                # Using markdown2 to convert to HTML then strip tags is a quick way to remove markdown syntax
                html_content = markdown2.markdown(content)
                text_content = ExportService.clean_html(html_content)
                document.add_paragraph(text_content)
            
            if section.get('bullets'):
                for bullet in section.get('bullets'):
                    document.add_paragraph(bullet, style='List Bullet')
            
            document.add_paragraph() # Spacing

        # Footer (Page numbers are tricky in python-docx without XML manipulation, skipping for MVP simplicity or adding simple footer text)
        section = document.sections[0]
        footer = section.footer
        paragraph = footer.paragraphs[0]
        paragraph.text = "AI Doc Builder Export"

        f = BytesIO()
        document.save(f)
        f.seek(0)
        return f

    @staticmethod
    def generate_pptx(project_data):
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = project_data.get('title', 'Untitled Project')
        subtitle.text = "Generated by AI Doc Builder"

        # Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        
        for section in project_data.get('outline', []):
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            title_shape.text = section.get('title', 'Untitled')
            
            tf = body_shape.text_frame
            
            # Add bullets (limit to 3-4 to fit)
            bullets = section.get('bullets', [])
            if bullets:
                for bullet in bullets[:4]:
                    p = tf.add_paragraph()
                    p.text = bullet
                    p.level = 0
            else:
                # If no bullets, try to summarize content or just show first sentence
                content = section.get('content', '')
                if content:
                    p = tf.add_paragraph()
                    p.text = content[:100] + "..."
            
            # Add notes
            notes_slide = slide.notes_slide
            text_frame = notes_slide.notes_text_frame
            text_frame.text = section.get('content', '')

        f = BytesIO()
        prs.save(f)
        f.seek(0)
        return f
